### ISSUE TITLE
Problem with WordAcceptorByKBMag

### ISSUE THREAD

**Issue by olexandr-konovalov** [gap-packages/kan#5]
Observed today in the master branch - needs investigation. Record it here for a reminder.
```
########> Diff in /circa/scratch/gap-jenkins/workspace/GAP-pkg-update-master-q\
uicktest/GAPCOPTS/64build/GAPGMP/gmp/GAPTARGET/packages/label/kovacs/GAP-pkg-u\
pdate-master-snapshot/pkg/kan-1.27/tst/fulltest.tst:157
# Input is:
waG3 := WordAcceptorByKBMag( G3, alph3 );;
# Expected output:
# But found:
Error, Could not open word-difference file
########
```
@cdwensley do you observe the same?

**Comment by cdwensley** [comment]
fulltest.tst gives me a large number of diffs, and then: 
gap> G3;   
<fp group on the generators [ a, b ]>
gap> alph3;
"AaBb"
gap> waG3 := WordAcceptorByKBMag( G3, alph3 );
/Applications/gap/my-dev/pkg/kbmag/bin/x86_64-apple-darwin16.7.0-gcc-default64/autgroup: line 133:  1065 Segmentation fault: 11  $GPMAKEFSA $gpmakefsaflags $groupname
#Program to construct word-acceptor and multiplier automata failed. Giving up.
Error, Word acceptor not available. called from
WordAcceptor( rws 
 ) at /Applications/gap/my-dev/pkg/kan/lib/dckbmag.gi:342 called from
<function "unknown">( <arguments> )
 called from read-eval loop at line 5 of *stdin*
you can 'quit;' to quit to outer loop, or
you can 'return;' to continue

**Comment by cdwensley** [comment]
Trying to make a new release of Kan but currently a host of issues with KBMag which Max is looking into - see KBMag issues.

**Comment by olexandr-konovalov** [comment]
yes, perhaps better to wait and coordinate with @fingolfin

**Comment by olexandr-konovalov** [comment]
No known problems with kan - will close.
